# Generated by Django 4.1.3 on 2022-12-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='rtg',
        ),
        migrations.AddField(
            model_name='game',
            name='predicted_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_winner', to='predict.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='predict.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='rd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='vol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(null=True),
        ),
    ]
