# Generated by Django 4.1.3 on 2022-12-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_remove_team_rtg_game_predicted_winner_game_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtg_history',
            name='team',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='rtg_history',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
