# Generated by Django 4.1.3 on 2022-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predict', '0003_remove_rtg_history_team_delete_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('confrence', models.CharField(max_length=100)),
                ('rating', models.FloatField(null=True)),
                ('rd', models.FloatField(null=True)),
                ('vol', models.FloatField(null=True)),
            ],
        ),
    ]
