# Generated by Django 4.1.3 on 2022-12-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_rtg_history_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
